POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "Richard",
  "name": "Adam Richard",
  "password": "rich",
  "gender": "male",
  "location": "Detroit"
}

###

POST http://localhost:3000/login 
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard@123"
}

###

PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "adam_richard",
  "oldPassword": "richard@123",
  "newPassword": "rich"
}